Tarefas/src/Tarefas.Web/Models/ErrorViewModel.cs
namespace Tarefas.Web.Models;

public class ErrorViewModel
{
    public string? RequestId { get; set; }

    public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
}

Tarefas/src/Tarefas.Web/Models/TarefaViewModel.cs
using System.ComponentModel;

namespace Tarefas.Web.Models;

public class TarefaViewModel
{
    public int Id { get; set; }
    
    [DisplayName("Título")]
    public string Titulo { get; set; }
    [DisplayName("Descrição")]
    public string Descricao { get; set; }
}

Tarefas/src/Tarefas.Web/Controllers/HomeController.cs
using System.Diagnostics;
using Microsoft.AspNetCore.Mvc;
using Tarefas.Web.Models;

namespace Tarefas.Web.Controllers;

public class HomeController : Controller
{
    private readonly ILogger<HomeController> _logger;

    public HomeController(ILogger<HomeController> logger)
    {
        _logger = logger;
    }

    public IActionResult Index()
    {
        return View();
    }

    public IActionResult Privacy()
    {
        return View();
    }

    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    public IActionResult Error()
    {
        return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
    }
}

Tarefas/src/Tarefas.Web/Controllers/TarefasController.cs
using Microsoft.AspNetCore.Mvc;
using Tarefas.Web.Models;

namespace Tarefas.Web.Controllers;

public class TarefasController : Controller
{
    public List<TarefaViewModel> listaDeTarefas { get; set; }
    public TarefasController()
        {
            listaDeTarefas = new List<TarefaViewModel>()
        {
            new TarefaViewModel() { Id = 1, Titulo = "Escovar os Dentes", Descricao = "Todas as manhãs"},
            new TarefaViewModel() { Id = 2, Titulo = "Arrumar a cama", Descricao = "Todas as manhãs"},
            new TarefaViewModel() { Id = 3, Titulo = "Tirar o lixo", Descricao = "Segunda, quarta e sexta"}
        };
        }
    public IActionResult Create()
    {
        return View();
    }

    public IActionResult Index()
    {
        
        return View(listaDeTarefas);
    }

    public IActionResult Details (int id)
    {
        var tarefa = listaDeTarefas.Find(tarefa=> tarefa.Id == id);
        return View(tarefa);
    }
}

Tarefas/src/Tarefas.Web/Views/Home/Criar tarefa.cshtml
@{
    ViewData["Title"] = "Criar Tarefa";
}
<h1>@ViewData["Title"]</h1>

<p>Use this page to detail your site's privacy policy.</p>

Tarefas/src/Tarefas.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Tarefas/src/Tarefas.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Tarefas.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Tarefas.Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Tarefas.Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tarefas" asp-action="Create">Criar Tarefa</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Tarefas" asp-action="Index">Lista de Tarefas</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Tarefas.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

Tarefas/src/Tarefas.Web/Views/Tarefas/Create.cshtml
@model Tarefas.Web.Models.TarefaViewModel

<form asp-action="Create">
    <div class="mb3">
        @Html.LabelFor(model => model.Titulo, new { @class = "form-label"})
        @Html.TextBoxFor(model => model.Titulo, new { @class = "form-control"})
     </div>

     <div class="mb3">
        @Html.LabelFor(model => model.Descricao, new { @class = "form-label"})
        @Html.TextBoxFor(model => model.Descricao, new { @class = "form-control"})
     </div>

     <input type="submit" />
</form>

Tarefas/src/Tarefas.Web/Views/Tarefas/Details.cshtml
@model Tarefas.Web.Models.TarefaViewModel

<form asp-action="Create">
    <div class="mb3">
        @Html.LabelFor(model => model.Titulo, new { @class = "form-label"})
        @Html.TextBoxFor(model => model.Titulo, new { @class = "form-control", @readonly = "readonly"})
     </div>

     <div class="mb3">
        @Html.LabelFor(model => model.Descricao, new { @class = "form-label"})
        @Html.TextBoxFor(model => model.Descricao, new { @class = "form-control", @readonly = "readonly"})
     </div>

<a asp-controller="Tarefas" asp-action="Index">Voltar</a>

</form>

Tarefas/src/Tarefas.Web/Views/Tarefas/Index.cshtml
@model IEnumerable<Tarefas.Web.Models.TarefaViewModel>

<table class="table">
  <thead>
    <tr>
      <th scope="col">#</th>
      <th scope="col">Tarefa</th>
      <th scope="col">Descricao</th>
      <th scope="col">Detalhes</th>
    </thead>
    @foreach (var item in Model)
    {
    <tr>
         <td>
            @item.Id
        </td>
        <td>
            @item.Titulo
        </td>
        <td>
            @item.Descricao
        </td>
        <td>
            <a asp-asp-controller="Tarefa" asp-action="Details" asp-route-id="@item.Id">Detalhes</a>
        </td>
    </tr>
    }
</table>